import "../styles/globals.css";
import HeaderPage from './../components/layout/HeaderPage';
import FooterPage from "./../components/layout/FooterPage";
export const metadata = {

  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
     <body>
       <HeaderPage/>
       {children}
       <FooterPage/>
       </body>
    </html>
  )
}
